//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 11:43:56 AM CEST 
//


package com.thalesgroup.optet.analysis.findbugs.jaxb.findbugs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatcherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatcherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatcherType")
@XmlSeeAlso({
    BugCodeMatcherType.class,
    FieldMatcherType.class,
    LocalMatcherType.class,
    RankMatcherType.class,
    MethodMatcherType.class,
    MatchMatcherType.class,
    BugMatcherType.class,
    NotMatcherType.class,
    PriorityMatcherType.class,
    OrMatcherType.class,
    ClassMatcherType.class,
    FirstVersionMatcherType.class,
    LastVersionMatcherType.class,
    BugPatternMatcherType.class,
    PackageMatcherType.class,
    AndMatcherType.class,
    DesignationMatcherType.class
})
public abstract class MatcherType {


}
